name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.6.0-alpine

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: apk add --no-cache libarchive-dev
    - name: Test
      run: crystal spec
    - name: Install static libraries
      run: apk add --no-cache libarchive-static acl-static expat-static zstd-static lz4-static bzip2-static
    - name: Test static build
      run: crystal build --static --release src/archive.cr
